# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:37
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20170813_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='order_placed', max_length=50),
        ),
    ]
